export const SITE_TITLE = 'DiskPress';
export const SITE_DESCRIPTION = 'Save space without deleting files. DiskPress combines native file compression and APFS file deduplication on your Mac, with background monitoring and a CLI.';
export const APP_STORE_URL = 'https://apps.apple.com/app/apple-store/id6800504458?pt=127627850&ct=www&mt=8';
export const DEVELOPER_URL = 'https://reverseeverything.com/ighor/?utm_source=diskpress.app';
export const BLOG_URL = 'https://reverseeverything.com/?utm_source=diskpress.app';
export const MORE_APPS_URL = 'https://reverseeverything.com/apps/?utm_source=diskpress.app';
export const APP_ARCHIVER_URL = 'https://apparchiver.com/?utm_source=diskpress.app';
export const SUPPORT_EMAIL = 'support@apptrust.app';
export const SUPPORT_ISSUES_URL = 'https://github.com/JulyIghor/DiskPress/issues';
export const CLI_BINARY = '/Applications/DiskPress.app/Contents/MacOS/DiskPress';
